AWSTemplateFormatVersion: 2010-09-09
Description: |
  Cloudformation Template for kittens carousel static website deploy on s3. cloudfront and route 53
Parameters:
  DomainName:
    Description: DNS Name of existing Amazon Route 53 hosted zone ex. clarusway.us
    Type: AWS::Route53::HostedZone::Id

  KittensDomainName:
    Description: Full domain name for the App. ex. kittens.clarusway.us
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)

Resources:

  KittensS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref KittensDomainName
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html

  KittensBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref KittensS3Bucket # Required
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: Allow
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref KittensS3Bucket
                - /*
            Principal: '*'

  KittensCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      CertificateTransparencyLoggingPreference: ENABLED
      DomainName: !Ref KittensDomainName # Required
      DomainValidationOptions:
        - DomainName: !Ref KittensDomainName
          HostedZoneId: !Ref DomainName
      ValidationMethod: DNS

  KittensCloudfront:
    Type: "AWS::CloudFront::Distribution" 
    Properties:
      DistributionConfig:
        Aliases:
        - !Ref KittensDomainName 
        Comment: Cloudfront Distribution pointing to Kittens S3 bucket
        DefaultCacheBehavior:
          AllowedMethods:  
          - GET
          - HEAD
          Compress: true
          ForwardedValues: 
            QueryString: true 
            Cookies:
              Forward: none 
          TargetOriginId: KittensOrigin  
          ViewerProtocolPolicy: allow-all 
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: 'http2'
        Origins: 
        - DomainName: !Select [2, !Split ["/", !GetAtt KittensBucket.WebsiteURL]] 
          Id: KittensOrigin
          CustomOriginConfig: 
            OriginProtocolPolicy: http-only 
        PriceClass: PriceClass_All
        ViewerCertificate:  
          AcmCertificateArn: !Ref KittensCertificate
          SslSupportMethod: sni-only

  KittenDNSName:
  Type: AWS::Route53::RecordSetGroup
  Properties:
    Comment: Creating records for Kittens Web Site
    HostedZoneId: !Ref DomainName
    RecordSets: 
        - Name: !Ref KittensDomainName
          Type: A
          AliasTarget:
            HostedZoneId: Z05779023PSDEC36VHLJE
            DNSName: !GetAtt KittensCloudfront.DomainName

Outputs:
  BucketName: 
    Description: S3 Bucket URL for Kittens Website
    Value: !GetAtt KittensBucket.WebsiteURL
  CloudfrontEndpoint:
    Description: Endpoint for Kittens Cloudfront
    Value: !GetAtt KittensCloudfront.DomainName
  FullDomainName:
    Description: Full Domain Name of my Application
    Value: !Ref KittensDomainName